wip

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -324,56 +324,56 @@ jobs:
         run: bash config/scripts/deploy.sh
       - name: Run deploy script x2
         run: bash config/scripts/deploy.sh
-  analyze:
-    name: CodeQL Analysis
-    runs-on: ubuntu-latest
-    environment: test
-    strategy:
-      fail-fast: false
-      matrix:
-        language: [javascript]
-    continue-on-error: true
-    steps:
-      - name: Check out main branch
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-      - name: Specify Docker Compose version
-        run: |
-          echo ""
-          echo "Installed version: $(docker compose version)"
-          version=2.6.0
-          docker compose version | grep --quiet "$version" || {
-            echo "Installing Docker Compose version $version ..."
-            mkdir -p ~/.docker/cli-plugins/
-            curl -SL "https://github.com/docker/compose/releases/download/v${version}/docker-compose-linux-x86_64" -o ~/.docker/cli-plugins/docker-compose
-            chmod +x ~/.docker/cli-plugins/docker-compose
-            echo "Installed version: $(docker compose version)"
-          }
-      - name: Configure Docker Compose
-        shell: bash
-        run: |
-          echo "Configuring Docker Compose..."
-          if [[ -f docker-compose.test.yml ]]; then
-            echo "Using docker-compose.test.yml for default overrides..."
-            cp docker-compose.test.yml docker-compose.override.yml
-          fi
-          echo "Done."
-      - name: Add hosts to /etc/hosts
-        shell: bash
-        run: |
-          hosts=("postgres" "redis" "elasticsearch")
-          echo "Updating hosts file..."
-          for host in "${hosts[@]}"; do
-            sudo echo "127.0.0.1 $host" | sudo tee -a /etc/hosts
-          done
-          echo "Done."
-      # - name: Initialize CodeQL
-      #   uses: github/codeql-action/init@v1
-      #   with:
-      #     languages: ${{ matrix.language }}
-      #     setup-python-dependencies: false
-      # - name: Autobuild
-      #   uses: github/codeql-action/autobuild@v1
-      # - name: Perform CodeQL Analysis
-      #   uses: github/codeql-action/analyze@v1
+  # analyze:
+  #   name: CodeQL Analysis
+  #   runs-on: ubuntu-latest
+  #   environment: test
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       language: [javascript]
+  #   continue-on-error: true
+  #   steps:
+  #     - name: Check out main branch
+  #       uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Specify Docker Compose version
+  #       run: |
+  #         echo ""
+  #         echo "Installed version: $(docker compose version)"
+  #         version=2.6.0
+  #         docker compose version | grep --quiet "$version" || {
+  #           echo "Installing Docker Compose version $version ..."
+  #           mkdir -p ~/.docker/cli-plugins/
+  #           curl -SL "https://github.com/docker/compose/releases/download/v${version}/docker-compose-linux-x86_64" -o ~/.docker/cli-plugins/docker-compose
+  #           chmod +x ~/.docker/cli-plugins/docker-compose
+  #           echo "Installed version: $(docker compose version)"
+  #         }
+  #     - name: Configure Docker Compose
+  #       shell: bash
+  #       run: |
+  #         echo "Configuring Docker Compose..."
+  #         if [[ -f docker-compose.test.yml ]]; then
+  #           echo "Using docker-compose.test.yml for default overrides..."
+  #           cp docker-compose.test.yml docker-compose.override.yml
+  #         fi
+  #         echo "Done."
+  #     - name: Add hosts to /etc/hosts
+  #       shell: bash
+  #       run: |
+  #         hosts=("postgres" "redis" "elasticsearch")
+  #         echo "Updating hosts file..."
+  #         for host in "${hosts[@]}"; do
+  #           sudo echo "127.0.0.1 $host" | sudo tee -a /etc/hosts
+  #         done
+  #         echo "Done."
+  # - name: Initialize CodeQL
+  #   uses: github/codeql-action/init@v1
+  #   with:
+  #     languages: ${{ matrix.language }}
+  #     setup-python-dependencies: false
+  # - name: Autobuild
+  #   uses: github/codeql-action/autobuild@v1
+  # - name: Perform CodeQL Analysis
+  #   uses: github/codeql-action/analyze@v1
